version: '3'

services:
  go-recorder:
    build:
      context: ./app/Dockerfile.recorder
    env_file:
      - ".env"
    volumes:
      - ./records:/records
    profiles:
      - manual # Обозначаем, что этот сервис не будет запускаться по умолчанию

  go-server:
    build:
      context: ./app/Dockerfile.server
    networks:
      - mynetwork
    env_file:
      - ".env"
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./records:/records
    restart: always
    privileged: true

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - mynetwork
    depends_on:
      - go-server
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/certs:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

