version: '3'

services:
  go-app:
    build:
      context: ./app
    networks:
      - mynetwork
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - mynetwork
    depends_on:
      - go-app
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/certs:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

  # go-app:
  #   image: golang:latest
  #   container_name: go-app
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   command: go run main.go
  #   ports:
  #     - "8080:8080"  # Проброс порта наружу
  #   depends_on:
  #     - selenium-hub
  #   networks:
  #     - grid
