# Используем официальный образ golang для сборки
FROM golang:1.23 AS builder

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем исходный код приложения
COPY . .
RUN go mod download

# Собираем приложение
RUN go build -o build/server ./cmd/server

WORKDIR /

# Сборка Go-приложения
# RUN go build -o build/main .
# CGO_ENABLED=0 GOOS=linux

ENTRYPOINT [ "/app/build/server" ]